import Head from 'next/head'
import { EB_Garamond } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import BossCard from '@/components/BossCard'

const EBGaramond = EB_Garamond({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Elden Ring - BossWiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${EBGaramond.className}`}>
        <Header />
        <BossCard />
      </main>
    </>
  )
}
