import Head from 'next/head'
import { BossSection } from '@/components/BossSection'
import { useContext } from 'react'
import { AppContext } from '@/context/AppContext'
import { NPCSection } from '@/components/NPCSection'

export default function Home() {
  const {page} = useContext(AppContext)

  return (
    <>
      <Head>
        <title>Elden Ring - Boss & NPC Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {page == 'boss' ? <BossSection /> : <NPCSection />}
      </main>
    </>
  )
}
